CREATE TABLE IF NOT EXISTS FILMS
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(255) NOT NULL,
    description  VARCHAR(200) NULL,
    release_date TIMESTAMP    NULL,
    duration     INT          NOT NULL,
    MPA          INT          NULL
);

CREATE TABLE IF NOT EXISTS MPA
(
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS film_rating
(
    film_id INT NOT NULL,
    MPA_id  INT NOT NULL,
    FOREIGN KEY (film_id) REFERENCES films (id),
    FOREIGN KEY (MPA_id) REFERENCES MPA (id)
);

CREATE TABLE IF NOT EXISTS genres
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS film_genre
(
    film_id  INT NOT NULL,
    genre_id INT NOT NULL,
    FOREIGN KEY (film_id) REFERENCES films (id),
    FOREIGN KEY (genre_id) REFERENCES GENRES (id)
);

CREATE TABLE IF NOT EXISTS users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login    VARCHAR(30) NOT NULL,
    email    VARCHAR(30) NOT NULL,
    birthday TIMESTAMP   NOT NULL,
    name     VARCHAR(30) NOT NULL
);
create unique index if not exists USER_EMAIL_UINDEX on USERS (email);
create unique index if not exists USER_LOGIN_UINDEX on USERS (login);

CREATE TABLE IF NOT EXISTS likes
(
    film_id INT NOT NULL,
    user_id INT NOT NULL,
    FOREIGN KEY (film_id) REFERENCES films (id),
    FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS friendship
(
    user_id   INT     NOT NULL,
    friend_id INT     NOT NULL,
    status    boolean NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (friend_id) REFERENCES users (id)
);


